/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\dell_computer_scan_lowpoly.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Dell(props) {
  const { nodes, materials } = useGLTF('/dell_computer_scan_lowpoly.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.DellComputer} position={[-0.092, -0.152, 0.906]} />
      </group>
    </group>
  )
}

useGLTF.preload('/dell_computer_scan_lowpoly.glb')

export default Dell