/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HometheaterSubwooffer.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
      const { nodes, materials } = useGLTF('/HometheaterSubwooffer.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} scale={[2.1, 1.9, 1.4]} />
    </group>
  )
}

useGLTF.preload('/HometheaterSubwooffer.gltf')

export default Model