/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 desk.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Desk(props) {
  const { nodes, materials } = useGLTF('./desk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube007.geometry} material={materials.Material} castShadow receiveShadow/>
    </group>
  )
}

useGLTF.preload('./desk.glb')

export default Desk