/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 desk.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Desk(props) {
  const { nodes, materials } = useGLTF('/desk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Wood.001']} position={[0, -0.028, 0.001]} scale={[0.09, 0.13, 0.036]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Wood.001']} position={[0, 0.17, 0]} scale={[1.201, 0.17, 0.5]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Wood.003']} position={[-0.805, 0.2, 0.017]} scale={[0.382, 0.179, 0.48]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Wood.002']} position={[0.805, 0.2, 0.017]} scale={[0.382, 0.179, 0.48]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Wood.004']} position={[-1.091, -1.247, 0]} scale={[0.022, 0.054, 0.339]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Wood.005']} position={[1.096, -1.247, 0]} scale={[0.022, 0.054, 0.339]} />
    </group>
  )
}

useGLTF.preload('/desk.glb')

export default Desk